title: Gimnasio "El Olimpo"
description: > # this means to ignore newlines until "baseurl:"
  El gimnasio "El Olimpo" tiene una amplia variedad de áreas de entrenamiento como máquinas, spinning, aeróbicos, baile, nutrición, spa, sauna, baño turco y piscina
permalink: ':title/'
baseurl: "/dante.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gimnasio "EL olimpo" # add your name
author-img: perfil gym.jpg # add your photo
about-author:  El gimnasio "El Olimpo" tiene una amplia variedad de áreas de entrenamiento como máquinas, spinning, aeróbicos, baile, nutrición, spa, sauna, baño turco y piscina. # add description
social-twitter: gymelolimpoec # add your Twitter handle
social-facebook: gimnasioelolimpo.ec # add your Facebook handle
social-github: Jeicok # add your Github handle


# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
